[package]
name = "complex-indifference"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["unicode-width"]
unicode-width = ["dep:unicode-width"]
no-unsafe = []

[dependencies]
unicode-width = { version = "0.2.0", optional = true }
