[package]
name = "mdf"
version = "0.1.0"
edition = "2021"
authors = ["George Pollard <porges@porg.es>"]
license = "GPL-3.0"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
gedcom = { path = "../gedcom" }
miette = { version = "7.2.0", features = ["fancy-no-backtrace"] }
tracing-subscriber = "0.3.18"
tracing = "0.1"
