[package]
name = "errful"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror = "1.0.63"
errful-derive = { path = "../errful-derive" }
